#### Modeling and Analysis

In [15]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
import random

In [7]:
# reading aisles dataset
aisles = pd.read_csv('data/aisles.csv')

In [8]:
# reading department dataset
department = pd.read_csv('data/departments.csv')

In [36]:
p = 0.50
all_orders = pd.read_csv('data/all_orders.csv', header = 0, skiprows = lambda i: i>0 and random.random() > p)

In [37]:
all_orders.head(2)

,product_id,product_name,aisle_id,department_id,order_id,add_to_cart_order,reordered,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,quantity
0,130,Vanilla Milk Chocolate Almond Ice Cream Bars M...,37,1,446766,20,1,126093,train,58,4,13,5.0,1.0
1,651,Organic Salted Butter,36,16,446766,4,1,126093,train,58,4,13,5.0,1.0

In [38]:
# create basket of products per order_id
basket = (all_orders
        .groupby(['order_id', 'product_name'])['quantity']
        .sum().unstack().reset_index().fillna(0)
        .set_index('order_id'))

MemoryError: Unable to allocate 4.04 GiB for an array with shape (14254, 38003) and data type float64

In [24]:
basket.shape

(11040, 5840)

In [26]:
# show a subset of columns
basket.iloc[:, [0, 1, 2, 3,4, 5, 6, 7]].head()

product_name,& Go! Hazelnut Spread + Pretzel Sticks,0% Fat Free Organic Milk,0% Fat Organic Greek Vanilla Yogurt,0% Fat Strawberry Greek Yogurt,0% Fat Vanilla Greek Yogurt,0% Greek Strained Yogurt,0% Greek Yogurt Black Cherry on the Bottom,1 % Lowfat Milk
order_id,,,,,,,,
456,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1198,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1506,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1591,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2068,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
def encode_units(x):
    if x <= 0:
        return 0
    if x >= 1:
        return 1

In [28]:
basket_sets = basket.applymap(encode_units)

In [31]:
basket_sets.head()

product_name,& Go! Hazelnut Spread + Pretzel Sticks,0% Fat Free Organic Milk,0% Fat Organic Greek Vanilla Yogurt,0% Fat Strawberry Greek Yogurt,0% Fat Vanilla Greek Yogurt,0% Greek Strained Yogurt,0% Greek Yogurt Black Cherry on the Bottom,1 % Lowfat Milk,1 Apple + 1 Mango Fruit Bar,1 Liter,...,Zesty Lemon Hommus,Zinc 50 mg,Zinfandel,Zipper Sandwich Bags,Zucchini Noodles,Zucchini Squash,"\""Constant Comment\"" Decaffeinated Black Tea Blend",of Hanover 100 Calorie Pretzels Mini,smartwater® Electrolyte Enhanced Water,with Crispy Almonds Cereal
order_id,,,,,,,,,,,,,,,,,,,,,
456,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1198,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1506,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1591,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2068,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [34]:
frequent_itemsets = apriori(basket_sets, min_support = 0.05, use_colnames = True)

In [35]:
frequent_itemsets.head()

Empty DataFrame
Columns: [support, itemsets]
Index: []